language: minimal

install:
  - brew update
  - brew install yadm


# Compiler selection
matrix:
  include:
    # Tests on osx
    - os: osx
      install: 
        - brew update
        - brew install yadm
        - brew unlink python@2

    - os: linux
      dist: xenial
      group: travis_latest
      install: 
        - mkdir ${HOME}/.local && export PATH=${HOME}/.local:$PATH
        - "curl -fLo ${HOME}/.local/bin/yadm \"https://github.com/TheLocehiliosan/yadm/raw/master/yadm\""
        - chmod a+x ${HOME}/.local/bin/yadm



script:
  - yadm clone --bootstrap https://github.com/PierreMarchand20/dotfiles.git
  - yadm bootstrap #to test idempotence