#!/bin/bash

set -e
# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"


if test "$(uname)" = "Darwin"
then
    if test ! $(which brew)
    then
        echo "  Installing Homebrew for you."
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    echo "Updating homebrew bundle"
    brew bundle --global --verbose
    echo "Applying preferences for macos"
    ./.macos
elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
then
    echo "Installing zsh and powerline fonts"
    apt update
    apt install -y  --no-install-recommends zsh fonts-powerline
    chsh -s /usr/bin/zsh root
fi


# Setup zim
export ZIM_HOME=${HOME}/.zim
zsh -c "source ~/.zim/zimfw.zsh install"


# Setup git
git config --global user.name 'Pierre Marchand'

git config --global core.editor 'code --wait'

git config --global merge.tool "vscode"
git config --global diff.tool "vscode"

git config --global mergetool.cmd 'code --wait $MERGED'
git config --global difftool.cmd 'code --wait --diff $LOCAL $REMOTE'

exit 0
