# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # # Run tests every month
  # schedule:
  #   - cron: '0 0 1 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu_mpich", "debian_mpich"]

    container: pierremarchand/scientific_development_env:${{ matrix.container }}

    name: CI Linux (${{ matrix.container }})

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run bootstrap
        run: |
          yadm clone --bootstrap https://github.com/PierreMarchand20/dotfiles.git
          yadm bootstrap
      - name: Run test
        run: |
          echo $0

  macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    name: CI macOS
    steps:
      - name: Install yadm
        run: brew install yadm
      - name: Run bootstrap
        run: |
          yadm clone --bootstrap https://github.com/PierreMarchand20/dotfiles.git
          yadm bootstrap
      - name: Run test
        run: |
          echo $0
