# This is a basic workflow to help you get started with Actions

name: CI_linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["pierremarchand/scientific_development_env:ubuntu_mpich", "pierremarchand/scientific_development_env:debian_mpich"]
        
    container: ${{ matrix.container }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          yadm clone --bootstrap https://github.com/PierreMarchand20/dotfiles.git
          yadm bootstrap
